name: publish

on:
  push:
    tags:
      - "v*.*.*"   # or "*.*.*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    environment: test

    permissions:
      id-token: write
      contents: write 

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: install uv
        uses: astral-sh/setup-uv@v7.1.6

      - name: install python
        run: uv python install 3.14.2

      - name: build
        run: uv build
      
      - name: gh-action-sigstore-python
        uses: sigstore/gh-action-sigstore-python@v3.3.0
        with:
          inputs: >-
            dist/*.tar.gz
            dist/*.whl

      - name: publish
        run: uv publish --index test-pypi

      - name: github release
        run: gh release create ${{ github.ref_name }} dist/* --title "${{ github.ref_name }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
